### ISSUE TITLE
Flex Reports V2

### ISSUE THREAD

**Issue by regiscamimura** [EASOL/easol#266]
Specs here: https://docs.google.com/document/d/1jkLYY2cybDFep6p5SCj6PC7Y2VI71qCXUy4wWszDwXQ/edit#heading=h.2eu7nmuhg0gg

- [x] 1. Flex Report add/edit form: Section for chart bars/slices definitions
- [x] - Create database table to store data - 1h
- [x] - Create named bars/slices, create JS to add items on the fly - 7h
- [x] - Color picker is postponed to a second phase
total: 8h

- [x] 2. Flex Reports presentation
- [x] - Create logic to group and sum data based on the result set for named columns - 8h
- [x] - Create similar logic for dynamic columns - 8h
- [x] - Create functions so a click on a bar/slice in the chart filters the table below - 6h
- [x] - Add a feature so a click on a bar/slice highlights it - 2h
- [x] - Removal of Easol_widget for filters - 4h
total: 28h

- [x] 3. Colors
- [x] - Implement color picker in add/edit form - 6h
- [x] - Implement the colors in flex report presentation - 8h
total: 14h

------
Additional @regiscamimura  - I have noticed that we yet don't have "reset" function on chart view (once you select a bar chart - then we need a way to see a full list again)

**Comment by regiscamimura** [comment]
@edgarf I just got pie charts implemented. I agree, we need a way to reset the filter. Should we have a button for "reset", or giving a second click on a slice/bar would remove the filter?

I also noted that we have an additional feature in pie charts, you can remove a slice from the chart by clicking the labels above. Should that also remove the related records from the table below?

**Comment by edgarf** [comment]
Thanks @regiscamimura, let's have a second click to get it reset maybe, and if possible - let's add a bigger highlight, cause now it's only slightly visible that the bar chart is selected.

Re pie charts - if possible and not too complicated - let's do this, thank you.

**Comment by edgarf** [comment]
@regiscamimura, just so I wouldn't forget, are there any special changes needed for the carabin file in the config? Or all of the values in .sample are good to be used in production?

**Comment by edgarf** [comment]
@regiscamimura - we probably need to add a task to fix representation on the /Dashboard view, is that right? (currently I see it's only table view there)

**Comment by edgarf** [comment]
@regiscamimura, one more issue - The detail view of pie/bar charts have no filters (table views seems to be working fine)

**Comment by regiscamimura** [comment]
@edgarf just got the legend filters implemented and the reset filter. I put the filters back to pie and bar charts and removed the easol_widget from it. Next step is to adjust the dashboard to use the proper functions.

============

for the carabiner.php file, there are some settings we should change for the production site:
$config['dev'] = false;
$config['combine'] = true;
$config['minify_js'] = true;
$config['minify_css'] = true;

The css and js will be unified and compressed, and saved to a cache folder, so you must make sure the system has permissions to write that folder, at ./assets/cache

**Comment by edgarf** [comment]
Hi @regiscamimura, thanks! 
So I assume we have left with:
1. Colors (for now let's use color codes, this field is missing in definition of defined slices) and additional ability to select "type" of color sequence for dynamic fields (for now just take the color sequence, which was in the web page I showed you before). 
2.  Dashboard page.

Sounds good.

**Comment by regiscamimura** [comment]
@edgarf I have the colors implemented, but we have some limitations there we should probably improve:

- For dynamic bars/slices, we have a hard-coded set of color options. What happens is that the hard-coded colors have only 5 options, and so if a chart has more than 5 bars/slices, the colors will repeat. Is that ok, or should I create an algorithm that will generate a gradient of colors so it will never repeat, just reduce the "distance" of the previous color as needed?
- Sometimes the color of a bar/slice can get really dark. Should I put a script to make the label text inside a slice white when the color is dark?

**Comment by edgarf** [comment]
@regiscamimura , thank you. I will test it tomorrow

1) Dynamic - are you saying we only have 5 different colors or the system only has the ability to keep 5 different ones?

2) Is it a complicated task?


Have you also done the dashboard view and ability for all users to see detail page? Thanks!

**Comment by edgarf** [comment]
@regiscamimura  Just checked - and I am getting "Invalid Report Display type" on the dashboard, do you think you'd be able to finish with these issues today?

**Comment by regiscamimura** [comment]
@edgarf Just got the dashboard fixed. I also implemented the permission rules changes so the detail page can be accessed by all users. With that, I believe this feature is done.

**Comment by edgarf** [comment]
Thank you @regiscamimura , I have done some testing and here are the comments below. 

- [ ] I had this query (below). As a "variable" I have added "BirthDate" and it was not working (maybe "as" part is not seen by the chart creation?).
```
SELECT StudentUSI, Student.FirstName, Student.LastSurname, SexType.CodeValue as Gender,  
Year(BirthDate) as BirthDate 
FROM edfi.Student JOIN edfi.SexType ON edfi.SexType.SexTypeId = Student.SexTypeId
```

- [ ] In the same query like above, I wanted to use "Student.LastSurname" as an aggregated value. However, it only worked when I entered "LastSurname". What if we are going to have multiple columns with the same names (just with different table prefixes?)

- [ ] Filters doesn't work now. I have tried adding different variations both "Student.FirstName" and "FirstName", this didn't work. You can fix this thing at the same time when you will apply this https://github.com/EASOL/easol/issues/273 task. I

 - [ ] I always get an error when I tap on "Preview" in the Flex Report edit view (even if there are no errors, when viewing the report). Example errors:
```
A PHP Error was encountered
Severity: Warning
Message: json_decode() expects parameter 1 to be string, array given

Filename: Reports/display-pie-chart.php
Line Number: 6

Backtrace:
File: D:\home\site\wwwroot\application\views\Reports\display-pie-chart.php
```

**Comment by regiscamimura** [comment]
@edgarf I got the error for saving the report to table, but I couldn't reproduce the other errors. I tried with my local database and also with the remote dev database. I see the filters working fine and the query you posted works fine too. Have you updated the database with the file ./sql/mssql/266-report-chart-table.sql?

Anyway, can you please send me an export of the report that is failing?

Regarding the preview feature, yes, I need to get back and implement the changes to it. It does NOT have the filters implemented neither. I'm assuming it's ok to work on that and get preview update, is that correct?

**Comment by edgarf** [comment]
Hey  @regiscamimura, thanks!

Have you tried going to the link in the comment? You'd be able to see all of those reports. And yes, I have run the SQL script.

The preview issue is having the lowest priority, let's solve everything else before that (including those new filter types).

**Comment by edgarf** [comment]
Actually, I just tested the point about aggregating "BirthYear" http://easol-dev.azurewebsites.net/reports/edit/67 and it started to work! Good. Though, the filters still don't work. I have exported one report https://www.dropbox.com/s/n92q1h7v2azbeh2/FILTER_DOESNT_WORK.json?dl=0 here. Please take a look. Thanks!

**Comment by regiscamimura** [comment]
@edgarf I took a look at that report, and remember, you MUST use the keyword for $filters in the command text, or even though the filters are set and displayed, they will NOT be applied to the query. So, in the command text field for that report, you must use: 

SELECT StudentUSI, Student.FirstName, Student.LastSurname, SexType.CodeValue as Gender,  Year(BirthDate) as BirthDate FROM edfi.Student JOIN edfi.SexType ON edfi.SexType.SexTypeId = Student.SexTypeId WHERE $filters

Is that the problem?

**Comment by edgarf** [comment]
Hey Regis, wow, that's my fault, sorry! And I will need to make sure I create a good instruction for other users. Thanks a lot for noticing it!

**Comment by regiscamimura** [comment]
@edgarf I just got the issue with multiple charts in the dashboard being the same.

**Comment by regiscamimura** [comment]
@edgarf Also got the preview feature fixed.

**Comment by edgarf** [comment]
@regiscamimura, we've been testing the reports. Those are great! Below is the list of adjustments which would be very useful for the user. Also, I will list some other Flex Reports related errors here in the list. Issues are listed in a priority order (the ones at the top are the most important ones)
- [ ] Let's add 3 more operators for "defined slices" - a) <= b) >= c) >= AND =<. This is needed because currently to properly define the intervals, this kind of "math" is needed (see screenshot below). Also this is needed in order to have ability to capture "zeros", since now, there is not way to capture interval which is between [0;1] for example. These 3 new operators would solve that.
![image](https://cloud.githubusercontent.com/assets/5213372/13665828/ee91a366-e6b6-11e5-9280-03b0341bd991.png)

- [ ] Some queries might take 30+ seconds to run (and it's ok). Let's just increase the limit up to 90 seconds for related controllers (I assume it's possible, correct?)

- [ ] If there is an SQL issue while submitting the Flex Report (our validation before saving), then all Filters and Slices are deleted, let's preserve those if it's not a very complicated task.

- [ ] The roles are repeated in the Flex Reports list. Please check what is the problem here
![image](https://cloud.githubusercontent.com/assets/5213372/13665902/6a2022be-e6b7-11e5-8a35-92ea3aa3f794.png) 

- [ ] When creating a category, it is created twice - two categories with the same title appears in the drop-down

- [ ]

**Comment by edgarf** [comment]
Good idea about cache, how much do you think it would take to get implemented?

Also, how much time do you think you'd need to finish with the rest of items?

Thanks a lot!

**Comment by regiscamimura** [comment]
@edgarf 8-12h for the cache implementation. The rest of the items will be done by tomorrow EOD.

**Comment by edgarf** [comment]
Great, thank you Regis. Let's not yet do Caching, though.

**Comment by regiscamimura** [comment]
@edgarf Regarding you question:

>  Is there any relation with the School column in the flex reports? Does it add any constraints?

Not really. The Reports are actually shared between schools. The related database fields are not really FK and have not actual constraints. 

The only thing that is different between schools is the dashboard configuration, when you can set different charts for each school, but you can just assign a report that have a value for SchoolId to any other School.

**Comment by regiscamimura** [comment]
@edgarf I added a feature so you now can use system variables in dynamic and static lists. I still have some issues to look at, related to your testing data, but I think I don't have access to the same dev database you're using. Could you please provide me that?

What I have now are these, FYI:
'hostname'     => 'oqc2uoyejf.database.windows.net',
'username'     => 'easol_dev_dba',
'password'     => '%Z!A8iVnH6e$OKMk',
'database'     => 'easol_dev'

**Comment by regiscamimura** [comment]
Also, FYI, while doing the fix to preserve data if a submit fails due to server-side validation, I also fixed the preview feature so it will show filters and links. If you use a filter, you'll get redirected to the actual report page. Should I fix that as well?

**Comment by edgarf** [comment]
Thank you for the updates @regiscamimura. I'm testing everything now and adding some new bugs I found after this update

- [ ] 1. When filter field is empty (when I just open the URL) it shows "Array" inside
![image](https://cloud.githubusercontent.com/assets/5213372/13751289/2593a4c8-ea12-11e5-8795-8637bf5ab6dd.png)
The filter is set-up this way:
![image](https://cloud.githubusercontent.com/assets/5213372/13751302/342ac714-ea12-11e5-9623-7b4817a29516.png)
- [ ] Maybe let's change the character which is used for "> AND <"? Since now I don't think we can have negative values there, is that right?

**Comment by edgarf** [comment]
@regiscamimura please also see some of the issues from previous messages - I have updated those (some resolutions found)

**Comment by regiscamimura** [comment]
@edgarf Notes:

1. The update you did is fine
2. Regarding this:

> When creating a category, it is created twice - two categories with the same title appears in the drop-down

I see that the database actually allows a report to be related to the same role more than once. There's no constraints, and the database accepts that just fine. And indeed there were duplicated values there, not sure how it got there to be honest. Maybe recent changes made existing records to loss the control over that. Anyway, the duplicated values won't cause any logic issue or error regarding permissions, and I added a function to group the roles so it won't show as duplicated values. 

Should I go ahead and fix the DB structure and code workflow anyway?

3. For this:
> Maybe let's change the character which is used for "> AND <"? Since now I don't think we can have negative values there, is that right?

I modified the character to be ";" instead of "-", is that ok? Also adjusted the client-side filtering to use negative values.

4. Regarding this:
> I also noticed, that if a cell is empty and we are using it for aggregating purposes, then it's being held as zero. Please see screenshots below, some of the rows didn't have the values in last column, but they were used as 0.

The database type for that column is actually nvarchar, not an integer, and the result from the database is an empty string, not zero. I don't see how we can make the code to "figure" when to cast an empty string (which type is actually string) to the integer zero.

What we can do is to make the query to have this convertion:
`SELECT
	StudentAttributes.*
	, AssessmentTitle
	, Version
	**,CONVERT(float, [Proficiency Level] ) as LEVEL**
FROM [EASOL].[NYCharterELA] AS VW
	INNER JOIN EASOL.StudentAttributes 
		ON VW.StudentUSI = StudentAttributes.StudentUSI 
WHERE $filters
ORDER BY 
	VW.StudentUSI`

**Comment by regiscamimura** [comment]
@edgarf I got the issues fixed. 

==========

I noted a layout issue though. Sometimes, the table may not fit in the screen, specially when we're on the preview modal window. When that happens, it overflows the available area and makes the browser to have a horizontal scrolling bar. 

We can (and probably should) update the datatable widget to make it responsive. By doing that, the table would not overflow, but it would have a horizontal scrolling within itself. Should I get that in place? 2-4h

**Comment by edgarf** [comment]
Hi @regiscamimura ,

Thanks for the reply.

1. Let’s do the update for the DB, if possible place it in this folder - /sql/mssql/incremental, we are adding files here which are needed for migration.

2. The “;” character sis good

3. Regarding “zero” and casting the empty string, I meant that if we use the report aggregation as integer (or decimal) and there are some empty values, those are added to the bar/slice which has zero value included. Could this be possible? We don’t need to add empty strings as zeros. The use case can be that we have a list of user scores and we need to aggregate it [0-4] [5-8] [9-10] some students might not have this test results at all, and (at least I think) the system now is adding those students to [0-4] interval.

5. Regarding responsive table view adaptation - we will review this tomorrow.


6. Thanks for putting all “checkboxes” into the issues above, I will look into tomorrow. 

Thanks a lot for your hard work!

**Comment by edgarf** [comment]
Hi @regiscamimura ,

so I’ve been doing some regression testing and found these two issues:
- [ ] When creating a report if it's a bar chart one and I try saving it - it doesn't save it shows me the same creation screen with command text but with empty filters and aggregation data without any errors. Seems like the only way to create it is to create a table report and then change it to a bar/pie type of report.

- [ ] Aggregation still doesn’t work if the variable has table name defined
```
SELECT StudentUSI, Student.FirstName, Student.LastSurname, SexType.CodeValue,  
Year(BirthDate) as BirthDate 
FROM edfi.Student JOIN edfi.SexType ON edfi.SexType.SexTypeId = Student.SexTypeId
```
Here, if I select SexType.CodeValue as variable - it won’t work, however it does if I just enter CodeValue

**Comment by regiscamimura** [comment]
@edgarf I got the creating issue fixed. There was a bug indeed when creating charts. I took advantage of this work and improved the chart reports there in terms of performance. The queries are indeed complex and take a while to process, and there was some other queries running to put the table columns and having the full result set instead of the aggregated, so I modified the workflow and it's now taking half of the time it was needed previously. 

Regarding this:

>  Aggregation still doesn’t work if the variable has table name defined

What happens is that the result of the query itself will NOT contain prefixed names. So if you run this query:

`SELECT StudentUSI, Student.FirstName, Student.LastSurname, SexType.CodeValue,  
Year(BirthDate) as BirthDate 
FROM edfi.Student JOIN edfi.SexType ON edfi.SexType.SexTypeId = Student.SexTypeId`

The DATABASE itself will return a result WITHOUT any prefix. Those prefix are only to prevent name collision. 

In the other hand, we do aggregating in PHP side, i.e., we first run the query, no aggregation, then we aggregate by columns. So when we do the aggregation the prefix are gone already, so we can't really use the prefix. 

Said that, I put a function to make PHP to handle the variable name and disregards any prefix or scaping characters, so you can now use SexType.CodeValue, but be aware it will NOT actually prevent override of values or anything. I mean, if the query has something like *SELECT SexType.CodeValue, Course.CodeValue* the actual result set will have TWO columns named *CodeValue* -- no prefix -- and so even if you use a variable name as *SexType.CodeValue*, PHP will actually just read *CodeValue* and so it will take the value of the last column named *CodeValue*. To avoid that, you must use alias in the query. Makes sense?

**Comment by edgarf** [comment]
@regiscamimura thanks. I understood re naming conventions, I will add this to the instruction, that if we have 2 identical Column names, then an alias is needed. There are going to be more enhancements to be done for the flex reports. However, for now, if you could - please just remove the "School" column form the Reports list, since it is not very useful. 

And additionally, please use development branch (you can branch off again or pull to your branch from there), I have done the file placement update for the SQL Migration. I see you haven't yet also added the file to update structure of the table you talked yesterday (the problem of duplicating roles) so please also put it into "incremental" folder.

**Comment by regiscamimura** [comment]
@edgarf all items in this task is done. I've added a sql file named 266-report-access-constraints.sql for the DB changes. I already run it in the dev database.

**Comment by edgarf** [comment]
Thanks.
